name: Bug Report
description: Report a bug to help us improve
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A clear description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: But instead...
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Environment
      description: What environment are you running Netmon in?
      options:
        - Docker Compose
        - Local Development
        - Kubernetes
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: OS
      description: Your operating system
      placeholder: Windows 11, macOS, Ubuntu 22.04, etc.

  - type: input
    attributes:
      label: Version
      description: Netmon version
      placeholder: 0.1.0

  - type: textarea
    attributes:
      label: Logs / Error Output
      description: Relevant log output or error messages
      render: shell

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, screenshots showing the issue

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context
